branch-defaults:
  develop:
    environment: Deephire-Node-Api-Prod
  master:
    environment: Deephire-Node-Api-Prod
environment-defaults:
  Deephire-Node-Api-Prod:
    branch: null
    repository: null
global:
  application_name: DeepHire
  default_ec2_keyname: aws-eb
  default_platform: Docker 17.03.1-ce
  default_region: us-east-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
