swagger: "2.0"
info:
  version: 1.0.0
  title: DeepHireNodeAPI
  description: Automate the recruiting process with one-way video interviews
basePath: /v1
tags:
  - name: Examples
    description: Simple example endpoints
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json

definitions:
  ExampleBody:
    type: object
    title: example
    required:
      - name
    properties:
      name:
        type: string
        example: no_stress
  EmailBody:
    type: object
    title: email
    required:
      - recipients
      - subject
      - message
    properties:
      recipients:
        # ArrayOfStr:
        type: array
        items:
          type: string
        example: ["russell@deephire.com"]
      subject:
        type: string
        example: testing
      message:
        type: string
        example: hey there
  CompanyBody:
    type: object
    title: company
    required:
      - email
    properties:
      email:
        type: string
        example: russell@deephire.com
      name:
        type: string
        example: Forge
      logo:
        type: string
        example: https://www.kiwiclubny.org/wordpress1/wp-content/uploads/2012/08/dub.logo_.url_.blk_1.jpg
  CandidateBody:
    type: object
    title: candidate
    required:
      - userId
    properties:
      userId:
        type: string
        example: testUserId99
      youtubeUrls:
        type: array
        items:
          type: string
        example:
          [
            "https://www.youTube.com/watch?v=QSmXvcrtTpM",
            "https://www.youTube.com/watch?v=emTHLFKcSWQ",
          ]
  ShortlistBody:
    type: object
    title: shortlist

    properties:
      userId:
        type: string
        example: uselessdata
      youtubeUrls:
        type: array
        items:
          type: string
        example: ["ar1", "ar3"]

  VideoBody:
    type: object
    title: video
    required:
      - userId
    properties:
      userId:
        type: string
        example: facebook|1948444908830936
      candidateEmail:
        type: string
        example: russell@test.com
      interviewId:
        type: string
        example: 5c4c8d0b7cebba000854883d
      userName:
        type: string
        example: Russell Ratcliffe
      responses:
        type: object
        title: responses
        properties:
          question:
            type: string
            example: whats your name?
          response:
            type: string
            example: https://video.com

paths:
  /examples:
    get:
      tags:
        - Examples
      description: Fetch all examples
      responses:
        200:
          description: Returns all examples
    post:
      tags:
        - Examples
      description: Create a new example
      parameters:
        - name: example
          in: body
          description: an example
          required: true
          schema:
            $ref: "#/definitions/ExampleBody"
      responses:
        201:
          description: Example Created

  /examples/{id}:
    get:
      tags:
        - Examples
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the example to retrieve
          type: integer
      responses:
        200:
          description: Return the example with the specified id
        404:
          description: Example not found

  /shortlists:
    get:
      parameters:
        - name: authorization
          in: header
          description: Bearer <auth_token>
          required: true
          type: string
      tags:
        - Shortlists
      description: Fetch all recruiter shortlist data
      responses:
        200:
          description: Returns all recruiter shortlist data
    post:
      tags:
        - Shortlists
      parameters:
        - name: authorization
          in: header
          description: Bearer <auth_token>
          required: true
          type: string
        - in: body
          name: body
          description: Create a new shortlist
          required: true
          schema:
            $ref: "#/definitions/ShortlistBody"
      responses:
        201:
          description: Resource created or updated
        500:
          description: Error!

  /shortlists/{id}:
    get:
      tags:
        - Shortlists
      parameters:
        - name: id
          in: path
          required: true
          description: The object id of the shortlist to fetch
          type: string
      responses:
        204:
          description: The shortlist with the specified ID was successfully fetched
        400:
          description: Malformed ID, the ID has to be a 12 character string
        404:
          description: Shortlist with given ID did not exist

  /videos:
    get:
      parameters:
        - name: authorization
          in: header
          description: Bearer <auth_token>
          required: true
          type: string
      tags:
        - Videos
      description: Fetch all video interviews
      responses:
        200:
          description: Returns all video interviews
    post:
      tags:
        - Videos
      description: Create or Update a Video
      parameters:
        - name: video
          in: body
          description: a video
          required: true
          schema:
            $ref: "#/definitions/VideoBody"
      responses:
        201:
          description: Video Created

  /videos/{id}:
    get:
      tags:
        - Videos
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the example to retrieve
          type: string
      responses:
        200:
          description: Return the example with the specified id
        404:
          description: Example not found
    delete:
      tags:
        - Videos
      parameters:
        - name: authorization
          in: header
          description: Bearer <auth_token>
          required: true
          type: string
        - name: id
          in: path
          required: true
          description: The users id
          type: string
      responses:
        204:
          description: The candidate video interview with the specified ID was successfully deleted
        400:
          description: Malformed ID, the ID has to be a 12 character string
        404:
          description: Candidate video unterview with given IDs did not exist

  /interviews:
    get:
      parameters:
        - name: authorization
          in: header
          description: Bearer <auth_token>
          required: true
          type: string
      tags:
        - Interviews
      description: Fetch all interviews
      responses:
        200:
          description: Returns all interviews

  /interviews/{id}:
    delete:
      tags:
        - Interviews
      parameters:
        - name: authorization
          in: header
          description: Bearer <auth_token>
          required: true
          type: string
        - name: id
          in: path
          required: true
          description: The object id of the interview to delete
          type: string
      responses:
        204:
          description: The interview with the specified ID was successfully deleted
        400:
          description: Malformed ID, the ID has to be a 12 character string
        404:
          description: Interview with given ID did not exist

  /candidates:
    put:
      tags:
        - Candidates
      description: Create/Update Candidate Data
      parameters:
        - name: authorization
          in: header
          description: Bearer <auth_token>
          required: true
          type: string
        - in: body
          name: body
          description: an example
          required: true
          schema:
            $ref: "#/definitions/CandidateBody"
      responses:
        200:
          description: Created or Updated Resource

  /candidates/{userId}:
    get:
      tags:
        - Candidates
      parameters:
        - name: userId
          in: path
          required: true
          description: The users auth0 ID
          type: string
      responses:
        200:
          description: Fetched the candidates info
        400:
          description: Malformed ID
        404:
          description: Candidate with given ID did not exist

  /emails:
    post:
      tags:
        - Emails
      parameters:
        - name: authorization
          in: header
          description: Bearer <auth_token>
          required: true
          type: string
        - in: body
          name: body
          description: "Send emails from russell@deephire.com"
          required: true
          schema:
            $ref: "#/definitions/EmailBody"
      responses:
        201:
          description: Email sent
        500:
          description: Error!

  /companies:
    get:
      parameters:
        - name: authorization
          in: header
          description: Bearer <auth_token>
          required: true
          type: string
      tags:
        - Companies
      description: Fetch all Company Data
      responses:
        200:
          description: Returns all company Data
    post:
      tags:
        - Companies
      parameters:
        - name: authorization
          in: header
          description: Bearer <auth_token>
          required: true
          type: string
        - in: body
          name: body
          description: "Add Company Name or Logo"
          required: true
          schema:
            $ref: "#/definitions/CompanyBody"
      responses:
        201:
          description: Info Added
        500:
          description: Error!

  /companies/{email}:
    get:
      tags:
        - Companies
      parameters:
        - name: authorization
          in: header
          description: Bearer <auth_token>
          required: true
          type: string
        - name: email
          in: path
          required: true
          description: The email of the company to retrieve
          type: string
      responses:
        200:
          description: Return the company with the associated email
        404:
          description: A Company with that email is not found
  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
